"""added PostContent and updated Post

Revision ID: 3912b955c00b
Revises: 4d62e114028f
Create Date: 2020-12-31 13:34:47.745406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3912b955c00b'
down_revision = '4d62e114028f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=8), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('uri', sa.String(length=128), nullable=True),
    sa.Column('css', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_contents_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_contents'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('published')

    op.drop_table('post_contents')
    # ### end Alembic commands ###
