"""added synonyms and antonyms

Revision ID: 51c18aee7cd4
Revises: 9b491bdd9c6f
Create Date: 2020-12-04 14:10:31.207588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c18aee7cd4'
down_revision = '9b491bdd9c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_antonyms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('_synonyms', sa.Text(), nullable=True))
        batch_op.alter_column('definition',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('example',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint('fk_nodes_parent_id_nodes', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_nodes_parent_id_nodes', 'nodes', ['parent_id'], ['id'])
        batch_op.alter_column('example',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('definition',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('_synonyms')
        batch_op.drop_column('_antonyms')

    # ### end Alembic commands ###
