"""added published field and made all fields nullable

Revision ID: b97dbf611301
Revises: 73d191dcfef7
Create Date: 2021-01-05 19:35:14.531502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97dbf611301'
down_revision = '73d191dcfef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('published')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('published')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('published')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.drop_column('published')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('published')

    # ### end Alembic commands ###
