"""added resource

Revision ID: bda2667b8244
Revises: 3912b955c00b
Create Date: 2021-01-02 11:35:13.002273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda2667b8244'
down_revision = '3912b955c00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('uri', sa.String(length=128), nullable=True),
    sa.Column('uri_title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
