"""added order to Node

Revision ID: f180338cc9e0
Revises: 2828d4765d5c
Create Date: 2021-01-15 14:45:45.528630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f180338cc9e0'
down_revision = '2828d4765d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
